version: '3.3'
services:
  app1:
    build:
      context: ./
      dockerfile: ./infra/app1/Dockerfile
    image: dc/httpd-hw1
    ports:
     - "8087:80"
    container_name: httpd-hw1
  app2:
    build:
      context: ./
      dockerfile: ./infra/app2/Dockerfile
    image: dc/httpd-hw2
    ports:
      - "8088:80"
    container_name: httpd-hw2