pipeline{
    agent {
        node {
            label 'master'
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr:'1'))
        disableConcurrentBuilds()
    }
    stages{
        stage('Deploy Apps') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/dcarbajosa/sfhttpd.git']]])
                sh "docker-compose up -d"      
            }
        }
    stage('Clean up') {
            steps {
                input "Exploratory Test"
            }
            post {
                always {
                    sh "docker-compose down"
		            sh "docker rmi dc/httpd-hw1"
		            sh "docker rmi dc/httpd-hw2"
                }
            }
        }
    }
    post {
        always {
            echo "deleteDir()"
        }
    }
}