pipeline{
    agent {
        node {
            label 'master'
        }
    }
    stages{
        stage('Deploy Apps') {
            sh "docker-compose up —d"      
	}
        stage('Clean up') {
            steps {
                input "Exploratory Test"
            }
            post {
                always {
                    sh "docker-compose down"
		    sh "docker rmi dc/httpd-hw1"
		    sh "docker rmi dc/httpd-hw2"
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}